workspace:
  base: /drone
  path: src
pipeline:
  #Restauramos la cache
  sftp_cache_restore:
    image: plugins/sftp-cache
    server: dev.byteflair.com:22
    path: /home/deployment/cache/repository/
    restore: true
    mount: /drone/.m2/
  build:
    image: maven:3-jdk-8
    commands:
    #Copiar settings de maven
     - if [ -d "/drone/.m2" ]; then
           cp -a /drone/.m2 /root ;
       fi
    #Copiar settings de maven
     - cp /drone/src/.drone/settings.xml /root/.m2
    #Limpiar y compilar
     - mvn -B -Djava.security.egd=file:/dev/./urandom -Ddocker.skip=true -Dspring.profiles.active=dev clean install
     - mvn -B sonar:sonar
     - cp -a /root/.m2 /drone
  deploy:
    image: maven:3-jdk-8
    commands:
     #Copiar settings de maven
     - if [ -d "/drone/.m2" ]; then
           cp -a /drone/.m2 /root ;
       fi
     #Copiar settings de maven
     - cp /drone/src/.drone/settings.xml /root/.m2
     - mvn -B -Dunit.skip=true -Dint.skip=true -Dmaven.install.skip=true -Ddocker.skip=true deploy -D jarName=
    when:
      event: tag
  sftp_cache_save:
    image: plugins/sftp-cache
    server: dev.byteflair.com:22
    path: /home/deployment/cache/repository/
    rebuild: true
    mount: /drone/.m2/
    when:
      status:  [ failure, success ]
services:
  postgresql:
    image: postgres:9.5
    environment:
     - POSTGRES_USER=oauth_server
     - POSTGRES_PASSWORD=password
     - POSTGRES_DB=oauth_db
    ports:
      "5432:5432"
  mysql:
    image: mysql:5.5
    environment:
     - MYSQL_USER=oauth_server
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_PASSWORD=password
     - MYSQL_DATABASE=oauth_db
    ports:
      "3306:3306"