spring:
  jpa:
    show-sql: false
    generate-ddl: false
  datasource:
    initialize: false
    schema: schema-${spring.datasource.platform}.sql
    data: data-${spring.datasource.platform}.sql
  data.rest:
    returnBodyOnCreate: true
    returnBodyOnupdate: true
server:
  port: 80
  # We need to use a diferent context path to avoid cookie collision in development when don't use different server names
  contextPath: /

---

spring:
  profiles: mysql
  jpa:
    database: MYSQL
  datasource:
    port: 3306
    platform: mysql
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.dbname}?autoReconnect=true&useUnicode=true&characterEncoding=utf8&noAccessToProcedureBodies=true&protocol=tcp
    driver-class-name: com.mysql.jdbc.Driver

---

spring:
  profiles: postgresql
  jpa:
    database: POSTGRESQL
  datasource:
    port: 5432
    platform: postgresql
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.dbname}?autoReconnect=true&useUnicode=true&characterEncoding=utf8&noAccessToProcedureBodies=true&protocol=tcp
    driver-class-name: org.postgresql.Driver

---

spring:
  profiles: pro
  datasource:
    host: set host property via env variable
    port: set port property via env variable
    dbname: set dbname property via env variable
    username: set username property via env variable
    password: set password property via env variable
logging.config: classpath:logback-production.xml

---

spring:
  profiles: dev
  jpa:
    show-sql: true
  datasource:
    #esto solo queremos que ocurra en test. Ejecuta schema-${spring.datasource.platform}.sql y data-${spring.datasource.platform}.sql
    initialize: true
    host: localhost
    dbname: oauth_db
    username: oauth_server
    password: password
keystore:
  path: classpath:keystore.jks
  password: password
  key:
    alias: dev_oauth_jwt_key
    password: password
server.port: 8080
logging:
  config: classpath:logback-development.xml
  level:
    com.gpsauriga.sso: DEBUG
    org.springframework.security: DEBUG
